# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a50957ed62747bab4375a7d2f4636284"
name = "sahil-test"
handle = "sahil-test-3"
application_url = "https://lets-wondering-starting-database.trycloudflare.com"
embedded = true

[webhooks] 
api_version = "2025-07"
 
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_products,write_discounts,write_pixels"

[auth]
redirect_urls = ["https://lets-wondering-starting-database.trycloudflare.com/auth/callback", "https://lets-wondering-starting-database.trycloudflare.com/auth/shopify/callback", "https://lets-wondering-starting-database.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://lets-wondering-starting-database.trycloudflare.com"
subpath = "check"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
